apiVersion: v1
kind: Service
metadata:
  name: cloudapp
spec:
  selector:
    app: cloudapp
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp
spec:
  selector:
    matchLabels:
      app: cloudapp
  replicas: 4
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
      containers:
        - name: cloudapp
          image: <acrname>.azurecr.io/cloudapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
